---
apiVersion: v1
kind: Namespace
metadata:
  name: ${SD_K8S_NAMESPACE}

---
apiVersion: v1
kind: Secret
metadata:
  name: build-cluster-worker-secrets
  namespace: ${SD_K8S_NAMESPACE}
  labels:
    k8s-app: build-cluster-worker
type: Opaque
stringData:
  username: ${SD_RABBITMQ_USERNAME}
  password: ${SD_RABBITMQ_PASSWORD}
